# Autogenerated by devscripts/update-version.py

__version__ = '2024.06.24.151059'

RELEASE_GIT_HEAD = 'a8520244b8642880e4d35925e9e49eff94d548de'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'ybtr/yt-dlp'

ORIGIN = 'ybtr/yt-dlp'

_pkg_version = '2024.06.24.151059'
